// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 IHP GmbH
//
// chiplet_format_io implementation. yaml-cpp (MIT) is used here and ONLY here;
// the public header stays dependency-clean.

#include "chiplet_format_io/chiplet_format_io.hpp"

#include <yaml-cpp/yaml.h>

#include <array>
#include <fstream>
#include <map>
#include <regex>
#include <sstream>
#include <utility>
#include <vector>

namespace chiplet_format_io {

namespace {

// --- the top-level block grammar -------------------------------------------
//
// Flow rule 4 (docs/CHIPLET_FORMAT_SPEC.md) says a host re-emits a flow block it
// did not author BYTE FOR BYTE. That is a statement about text, so `flow_yaml`
// is the source slice and not a re-serialisation: YAML::Dump re-quotes scalars
// by the emitter's rules (a source '0755' comes back bare and is an integer to
// the next PyYAML reader) and drops comments, which in a hand-written flow carry
// the author's intent. The grammar is normative in the spec under "Top-level
// block grammar", and every implementation of it is measured against
// conformance/fixtures/top_level_blocks_cases.json rather than against another
// implementation. No YAML is parsed by any of this, on purpose.

// --- the line-break set ----------------------------------------------------
//
// The format's line breaks are LF and CRLF (docs/CHIPLET_FORMAT_SPEC.md, "Line
// breaks"). The set below is not a list somebody wrote down: it is generated by
// a criterion, and the criterion is that a YAML parser breaks a line on the
// character and THIS GRAMMAR does not, so the parser sees a top-level key that
// the grammar, and therefore SPEC-14's repeated-key scan and every splitting
// host, cannot. The Python side derives the members by execution
// (conformance/test_top_level_blocks.py runs PyYAML over a code-point range);
// this file carries the same four because it is measured against the same
// oracle, never against a list.
//
// NEL, U+2028 and U+2029 are ill-formed ANYWHERE. CR is the fourth member and
// the only conditional one, handled on its own below: CRLF is the other line
// break, so a CR is ill-formed exactly when the next byte is not LF.
//
// Measured on PyYAML 6.0.3 and yaml-cpp 0.8.0, and the disagreement runs both
// ways: `name: demo<LS>` followed by `format_version: "9.0"` gives PyYAML a
// second top-level key (format_version '9.0') and yaml-cpp an "illegal map
// value" throw, while the same separator followed by ordinary text loads in
// yaml-cpp with the three bytes inside the scalar and throws a ScannerError in
// PyYAML. A lone CR does the same in both shapes, the difference being that
// yaml-cpp folds it to a space instead of keeping it, so it changes the VALUE
// rather than preserving it. Neither reader can be made to imitate the other,
// so the text is refused before either of them sees it.
struct ForbiddenLineBreak {
    const char* utf8;
    const char* name;
    const char* code_point;
    const char* escape;
};
const std::array<ForbiddenLineBreak, 3> kForbiddenLineBreaks = {{
    {"\xC2\x85", "Unicode next line", "U+0085", "\\N"},
    {"\xE2\x80\xA8", "Unicode line separator", "U+2028", "\\L"},
    {"\xE2\x80\xA9", "Unicode paragraph separator", "U+2029", "\\P"},
}};

// Refuse a document carrying one of the four, naming the code point and the
// line. Runs on the TEXT, ahead of yaml-cpp: on such a document yaml-cpp either
// throws with a message about a map value, which says nothing about the real
// defect, or accepts bytes PyYAML refuses. All four are invisible in an editor,
// so a bare "invalid document" would send the author looking at the wrong thing.
//
// A CR at END OF FILE with no LF after it is refused as well. That case is
// decided in the spec rather than left to line_content(), which pops a trailing
// CR whether or not an LF follows and would otherwise read one byte less than
// the file holds without saying so.
void check_line_breaks(const std::string& text) {
    int line = 1;
    for (std::size_t i = 0; i < text.size(); ++i) {
        if (text[i] == '\n') { ++line; continue; }
        if (text[i] == '\r') {
            if (i + 1 < text.size() && text[i + 1] == '\n') continue;
            throw ChipletFormatError(
                "line " + std::to_string(line) + ": carriage return (U+000D) "
                "not followed by LF. A document's line breaks are LF and CRLF, "
                "so a CR is legal only as the first byte of a CRLF, end of file "
                "included. PyYAML 6.0.3 and yaml-cpp 0.8.0 both break a line on "
                "a lone CR and this grammar does not, so a top-level key written "
                "after one is invisible to every consumer that splits the text "
                "on LF, this reader's own repeated-key scan included. Escape it "
                "in a double-quoted scalar (\\r) "
                "(docs/CHIPLET_FORMAT_SPEC.md, top-level block grammar).");
        }
        for (const ForbiddenLineBreak& bad : kForbiddenLineBreaks) {
            const std::size_t len = std::char_traits<char>::length(bad.utf8);
            if (text.compare(i, len, bad.utf8) != 0) continue;
            throw ChipletFormatError(
                "line " + std::to_string(line) + ": " + bad.name + " (" +
                bad.code_point + ") inside a scalar. A document's line breaks "
                "are LF and CRLF. A YAML 1.1 parser (PyYAML) treats NEL "
                "(U+0085), LS (U+2028) and PS (U+2029) as line breaks and a "
                "YAML 1.2 parser (yaml-cpp) does not, so the same bytes are two "
                "different documents and neither reading is conforming. Escape "
                "it in a double-quoted scalar (\\N, \\L, \\P) "
                "(docs/CHIPLET_FORMAT_SPEC.md, top-level block grammar).");
        }
    }
}

bool has_forbidden_line_break(const std::string& text) {
    for (const ForbiddenLineBreak& bad : kForbiddenLineBreaks) {
        if (text.find(bad.utf8) != std::string::npos) return true;
    }
    return false;
}

// A KEY LINE: a bare key at column zero, optionally followed by whitespace and a
// value or a comment. Used with regex_match, which anchors both ends, so there
// is no end anchor to get wrong ($ is wrong in Python, \Z does not exist in
// ECMAScript). ECMAScript's dot excludes CR as well as LF, so this writes [^\n]
// where the spec's canonical spelling writes a dot; on a line, which carries no
// LF, the two mean the same thing.
const std::regex& key_line_re() {
    static const std::regex re(
        R"RX(([A-Za-z0-9_][A-Za-z0-9_.-]*):(?:\s[^\n]*)?)RX");
    return re;
}

// A QUOTED key at column zero. Valid YAML, not a key line, and the reason a
// splitting host refuses to SPLIT the document instead of attaching the block to
// the preceding key, whose owner regenerates it away on the next export. The
// document still loads: the spelling is structurally fine, it is the text-level
// ownership question that has no answer.
const std::regex& quoted_key_line_re() {
    static const std::regex re(
        R"RX((?:"(?:[^"\\]|\\.)*"|'(?:[^']|'')*'):(?:\s[^\n]*)?)RX");
    return re;
}

// A BLOCK SEQUENCE ENTRY at column zero: `-` followed by a space, a tab or
// nothing. Not a key line, and the one non-key line at column zero that IS
// attributable: PyYAML writes a block sequence under a mapping key at the
// parent's indentation, so `components:` followed by `- id: ...` lines is what
// every generated document in this ecosystem looks like. The entry belongs to
// the key whose block it sits in, and the splitter and a parser agree that it
// does.
const std::regex& sequence_entry_re() {
    static const std::regex re(R"RX(-(?:[ \t][^\n]*)?)RX");
    return re;
}

// A document marker, `---` or `...`, alone or introducing a value. Not a key
// line: it stays in the current block, or the preamble before the first key.
const std::regex& document_marker_re() {
    static const std::regex re(R"RX((?:---|\.\.\.)(?:[ \t][^\n]*)?)RX");
    return re;
}

// The part of a line the grammar matches: no LF, one optional trailing CR
// removed, so a CRLF document reads exactly like an LF one.
std::string line_content(const std::string& line) {
    std::string content = line;
    if (!content.empty() && content.back() == '\n') content.pop_back();
    if (!content.empty() && content.back() == '\r') content.pop_back();
    return content;
}

// The top-level key `content` opens, or "" when it is not a key line.
std::string top_level_key(const std::string& content) {
    std::smatch match;
    if (!std::regex_match(content, match, key_line_re())) return std::string();
    return match[1].str();
}

// Is this line content at column zero with no top-level key that owns it?
//
// The generalisation of the quoted-key rule, and the property it protects is the
// one SPEC-36 named: the split and the parse must not disagree about a
// document's top-level keys. A line at column zero that is not a key line starts
// no block, so a splitter attaches it to the PRECEDING key, whose owner
// regenerates it away on the next re-export, while a YAML parser reads a
// top-level key the split never saw.
//
// Column zero is "does not start with a space". A tab is therefore column zero,
// deliberately: this grammar has no notion of tab indentation, and YAML has none
// either in block context (measured on PyYAML 6.0.3 and yaml-cpp 0.8.0: both
// refuse a tab-indented mapping outright), so a tab-led line is never one an
// implementation may quietly attribute to the open block.
//
// Five shapes at column zero are attributable and are not this: a blank line, a
// comment (`#`) or a directive (`%`), a document marker, a block sequence entry,
// and a key line.
bool is_unattributable(const std::string& content) {
    if (content.find_first_not_of(" \t") == std::string::npos) {
        return false;
    }
    const char first = content[0];
    if (first == ' ' || first == '#' || first == '%') return false;
    if (std::regex_match(content, document_marker_re())) return false;
    if (std::regex_match(content, sequence_entry_re())) return false;
    return top_level_key(content).empty();
}

// Put the document's top-level keys back to bare after a pass that quoted every
// string. The grammar's writer rule (docs/CHIPLET_FORMAT_SPEC.md, "Top-level
// keys are written bare") is what lets any host split the file, and no writer
// here may break it to satisfy another rule. The rewrite is exact rather than
// hopeful: only this writer's own literal key names ever reach column zero (every
// data-derived key is nested), and a line is un-quoted precisely when the
// unquoted form is a key line under the grammar above. Nested keys keep their
// quotes, which the grammar has nothing to say about.
std::string unquote_top_level_keys(const std::string& text) {
    std::string out;
    std::size_t start = 0;
    while (start < text.size()) {
        const std::size_t nl = text.find('\n', start);
        const std::size_t end = (nl == std::string::npos) ? text.size() : nl + 1;
        std::string line = text.substr(start, end - start);
        const std::string content = line_content(line);
        const std::size_t close = content.find("\":");
        if (!content.empty() && content[0] == '"' && close != std::string::npos) {
            const std::string bare =
                content.substr(1, close - 1) + content.substr(close + 1);
            if (!top_level_key(bare).empty()) {
                line = bare + line.substr(content.size());
            }
        }
        out += line;
        start = end;
    }
    return out;
}

// Split a document into its top-level blocks, in document order, each one the
// exact source text: key line included, original line endings, no
// trailing-newline normalisation, nothing stripped. Lines before the first key
// line are the PREAMBLE, keyed by the empty string, and are present only when
// there are any.
//
// Two outcomes that are not a successful split, and they are different things:
//
//   * an UNATTRIBUTABLE line at column zero makes the document NOT SPLITTABLE:
//     a quoted key, an explicit key (`? ...`), a bare key outside the grammar
//     (`a b:`), or anything else there that is not a key line, a comment, a
//     directive, a document marker or a block sequence entry. It is valid YAML
//     and a reader must still load it (flow rule 1), so this is reported through
//     `not_splittable` rather than thrown: the blocks returned alongside it
//     mis-attribute those bytes to the preceding block and no caller may use
//     them.
//   * a REPEATED top-level key makes the document ill-formed, and that one
//     throws. PyYAML resolves such a key to the last value and yaml-cpp to the
//     first, so no reading of it is conforming and there is nothing to hand back.
std::vector<std::pair<std::string, std::string>> split_top_level_blocks(
    const std::string& text, std::string* not_splittable = nullptr) {
    std::vector<std::pair<std::string, std::string>> blocks;
    blocks.emplace_back(std::string(), std::string());  // the preamble
    std::size_t current = 0;
    std::size_t start = 0;
    // Lines end at LF, full stop. Anything wider (CR, VT, FF, NEL, U+2028) would
    // grow a top-level block that is not in the file.
    for (int number = 1; start < text.size(); ++number) {
        const std::size_t nl = text.find('\n', start);
        const std::size_t end = (nl == std::string::npos) ? text.size() : nl + 1;
        const std::string line = text.substr(start, end - start);
        const std::string content = line_content(line);
        const std::string key = top_level_key(content);
        if (!key.empty()) {
            for (const auto& block : blocks) {
                if (block.first == key) {
                    throw ChipletFormatError(
                        "line " + std::to_string(number) +
                        ": repeated top-level key (" + key +
                        "). A document names each top-level key once. PyYAML "
                        "resolves a repeat to the LAST value and yaml-cpp to the "
                        "FIRST, so two conforming readers read different "
                        "documents from these bytes, and neither the schema nor "
                        "a parsed node tree can see that it happened "
                        "(docs/CHIPLET_FORMAT_SPEC.md, top-level block grammar).");
                }
            }
            blocks.emplace_back(key, std::string());
            current = blocks.size() - 1;
        } else if (is_unattributable(content) && not_splittable != nullptr &&
                   not_splittable->empty()) {
            if (std::regex_match(content, quoted_key_line_re())) {
                *not_splittable =
                    "line " + std::to_string(number) +
                    ": quoted key at column zero (" + content +
                    "). A quoted key is valid YAML but does not start a "
                    "top-level block, so this document cannot be split without "
                    "attaching the block to the preceding key, where its owner "
                    "drops it on the next re-export. Emit bare keys and quote "
                    "values "
                    "(docs/CHIPLET_FORMAT_SPEC.md, top-level block grammar).";
            } else {
                *not_splittable =
                    "line " + std::to_string(number) +
                    ": unattributable line at column zero (" + content +
                    "). It is not a key line, and not a comment, a document "
                    "marker, a directive or a block sequence entry either, so "
                    "the line grammar cannot establish ownership. Guessing can "
                    "hide a top-level key or misinterpret a quoted scalar "
                    "continuation. Two problematic key spellings the Python "
                    "emitter can produce for a key it cannot write bare are the explicit "
                    "key (`? ...` with its `: ...` value line) and a bare key "
                    "outside the grammar (`a b:`). Emit top-level keys as key "
                    "lines and re-emit quoted scalar continuations with a conforming writer "
                    "(docs/CHIPLET_FORMAT_SPEC.md, top-level block grammar).";
            }
        }
        blocks[current].second += line;
        start = end;
    }
    if (blocks.front().second.empty()) blocks.erase(blocks.begin());
    return blocks;
}

// Read an optional scalar, returning `fallback` when the key is absent or null.
template <typename T>
T as_or(const YAML::Node& node, const char* key, const T& fallback) {
    const YAML::Node child = node[key];
    if (!child || child.IsNull()) {
        return fallback;
    }
    return child.as<T>(fallback);
}

Position3D parse_position(const YAML::Node& node) {
    Position3D p;
    p.x = as_or<double>(node, "x", 0.0);
    p.y = as_or<double>(node, "y", 0.0);
    p.z = as_or<double>(node, "z", 0.0);
    return p;
}

Rotation3D parse_rotation(const YAML::Node& node) {
    Rotation3D r;
    r.z = as_or<double>(node, "z", 0.0);
    return r;
}

Dimensions3D parse_dimensions(const YAML::Node& node) {
    Dimensions3D d;
    d.width = as_or<double>(node, "width", 0.0);
    d.height = as_or<double>(node, "height", 0.0);
    d.thickness = as_or<double>(node, "thickness", 0.0);
    return d;
}

Technology parse_technology(const std::string& id, const YAML::Node& node) {
    Technology tech;
    tech.id = id;
    tech.description = as_or<std::string>(node, "description", "");
    tech.layer_properties = as_or<std::string>(node, "layer_properties", "");
    tech.stackup = as_or<std::string>(node, "stackup", "");
    if (node["dbu"] && !node["dbu"].IsNull()) {
        tech.dbu = node["dbu"].as<double>(0.001);
        tech.has_dbu = true;
    }
    return tech;
}

Component parse_component(const YAML::Node& node) {
    if (!node.IsMap()) {
        throw ChipletFormatError("component entry must be a mapping");
    }
    Component c;

    // id and type are hard-required by the format (a component without them is
    // meaningless); throw unconditionally, mirroring the C++ host reader.
    if (!node["id"] || node["id"].IsNull()) {
        throw ChipletFormatError("component missing required field: id");
    }
    c.id = node["id"].as<std::string>();

    if (!node["type"] || node["type"].IsNull()) {
        throw ChipletFormatError("component '" + c.id +
                                 "' missing required field: type");
    }
    c.type = node["type"].as<std::string>();

    c.technology = as_or<std::string>(node, "technology", "");
    c.connection = as_or<std::string>(node, "connection", "");
    c.layout = as_or<std::string>(node, "layout", "");

    // cells: new `cells` (sequence or scalar) or legacy `top_cell` scalar.
    if (node["cells"]) {
        const YAML::Node& cells = node["cells"];
        if (cells.IsSequence()) {
            for (const auto& cell : cells) {
                c.cells.push_back(cell.as<std::string>());
            }
        } else if (!cells.IsNull()) {
            c.cells.push_back(cells.as<std::string>());
        }
    } else if (node["top_cell"] && !node["top_cell"].IsNull()) {
        c.cells.push_back(node["top_cell"].as<std::string>());
    }

    if (node["position"]) c.position = parse_position(node["position"]);
    if (node["rotation"]) c.rotation = parse_rotation(node["rotation"]);
    c.orientation = as_or<std::string>(node, "orientation", "");

    if (node["anchor"] && !node["anchor"].IsNull()) {
        c.anchor = node["anchor"].as<std::string>();
    }

    if (node["dimensions"]) c.dimensions = parse_dimensions(node["dimensions"]);

    // Optional interposer die-attachment surface z. Absent => nullopt, and
    // consumers fall back to dimensions.thickness (legacy mount reference).
    if (node["attachment_surface_z"] && !node["attachment_surface_z"].IsNull()) {
        c.attachment_surface_z = node["attachment_surface_z"].as<double>();
    }

    if (node["array"]) {
        const YAML::Node& a = node["array"];
        ComponentArray arr;
        arr.pattern = as_or<std::string>(a, "pattern", "");
        if (a["count"]) {
            arr.count_x = as_or<int>(a["count"], "x", 0);
            arr.count_y = as_or<int>(a["count"], "y", 0);
        }
        if (a["pitch"]) {
            arr.pitch_x = as_or<double>(a["pitch"], "x", 0.0);
            arr.pitch_y = as_or<double>(a["pitch"], "y", 0.0);
        }
        if (a["start_position"]) {
            arr.start_position = parse_position(a["start_position"]);
        }
        c.array = arr;
    }

    if (node["metadata"] && node["metadata"].IsMap()) {
        for (const auto& kv : node["metadata"]) {
            c.metadata.emplace_back(kv.first.as<std::string>(),
                                    kv.second.as<std::string>());
        }
    }

    if (node["io_pads"] && node["io_pads"].IsSequence()) {
        for (const auto& padNode : node["io_pads"]) {
            IOPad pad;
            pad.id = as_or<std::string>(padNode, "id", "");
            pad.io_class = as_or<std::string>(padNode, "io_class", "");
            pad.net = as_or<std::string>(padNode, "net", "");
            if (padNode["position"]) {
                pad.pos_x = as_or<double>(padNode["position"], "x", 0.0);
                pad.pos_y = as_or<double>(padNode["position"], "y", 0.0);
            }
            if (padNode["size"]) {
                pad.size_x = as_or<double>(padNode["size"], "x", 0.0);
                pad.size_y = as_or<double>(padNode["size"], "y", 0.0);
            }
            pad.layer = as_or<std::string>(padNode, "layer", "");
            c.io_pads.push_back(std::move(pad));
        }
    }

    return c;
}

ConnectionStack parse_connection_stack(const std::string& id,
                                       const YAML::Node& node) {
    ConnectionStack stack;
    stack.id = id;
    stack.description = as_or<std::string>(node, "description", "");
    if (node["layers"] && node["layers"].IsSequence()) {
        for (const auto& layerNode : node["layers"]) {
            ConnectionStackLayer layer;
            layer.name = as_or<std::string>(layerNode, "name", "");
            layer.material = as_or<std::string>(layerNode, "material", "");
            layer.height = as_or<double>(layerNode, "height", 0.0);
            layer.diameter = as_or<double>(layerNode, "diameter", 0.0);
            stack.layers.push_back(std::move(layer));
        }
    }
    return stack;
}

// Validation rule 8's table (spec, "Usage class and interface type"): which
// interface types a pad of a given io_class may take part in. One row per
// io_class, nullptr-padded because the rows are not the same length.
// conformance/test_pad_usage_compatibility.py reads this literal, the spec table
// and the Python IO_CLASS_INTERFACE_TYPES, so a row that moves in one place
// alone fails there rather than travelling.
struct PadUsageRow {
    const char* io_class;
    std::array<const char*, 3> allowed;
};
const std::array<PadUsageRow, 3> kPadUsageTable = {{
    {"wire_bond", {"wire_bond", nullptr, nullptr}},
    {"flipped_bump", {"micro_bump", "copper_pillar", "solder_bump"}},
    {"tsv_bump", {"tsv", nullptr, nullptr}},
}};

const PadUsageRow* pad_usage_row(const std::string& io_class) {
    for (const auto& row : kPadUsageTable) {
        if (io_class == row.io_class) return &row;
    }
    return nullptr;
}

std::string allowed_list(const PadUsageRow& row) {
    std::string out;
    for (const char* t : row.allowed) {
        if (t == nullptr) continue;
        if (!out.empty()) out += ", ";
        out += t;
    }
    return out;
}

// Rule 8, on the one endpoint the document can answer for: the one whose
// component carries inline io_pads (today the interposer). The endpoint's pad
// set is the inline pads on the endpoint's port_layer; an empty set is vacuous,
// and a die endpoint carries no pads in the document at all, so it is out of
// scope by decision until an explicit pad binding exists (SPEC-24). A pad whose
// io_class is outside the table is not judged here; that vocabulary is closed by
// the schema.
//
// An unrecognised interface TYPE is skipped for the same reason and by the same
// shape of test, and that symmetry is a fix rather than a tidy-up: this was the
// THIRD place the library refused an unknown type, and the one that survived
// removing the other two, because a type outside the table matches no allowed
// entry and so came out as a violation instead of as a value the rule has
// nothing to say about. Rule 8 relates two CLOSED vocabularies; a member of
// neither is outside its domain, not in breach of it.
void check_pad_usage(const ChipletDocument& doc) {
    for (const auto& iface : doc.interfaces) {
        if (!is_known_interface_type(iface.type)) continue;
        const InterfaceEndpoint* endpoints[2] = {
            iface.from ? &iface.from.value() : nullptr,
            iface.to ? &iface.to.value() : nullptr};
        for (const InterfaceEndpoint* ep : endpoints) {
            if (ep == nullptr) continue;
            for (const auto& comp : doc.components) {
                if (comp.id != ep->component) continue;
                for (const auto& pad : comp.io_pads) {
                    if (pad.layer != ep->port_layer) continue;
                    const PadUsageRow* row = pad_usage_row(pad.io_class);
                    if (row == nullptr) continue;
                    bool ok = false;
                    for (const char* t : row->allowed) {
                        if (t != nullptr && iface.type == t) ok = true;
                    }
                    if (!ok) {
                        throw ChipletFormatError(
                            "interface '" + iface.id + "' of type '" +
                            iface.type + "' meets pad '" + pad.id +
                            "' (io_class '" + pad.io_class + "') on layer '" +
                            pad.layer + "' of component '" + comp.id +
                            "': io_class '" + pad.io_class + "' allows only " +
                            allowed_list(*row) +
                            " (docs/CHIPLET_FORMAT_SPEC.md, validation rule 8)");
                    }
                }
            }
        }
    }
}

InterfaceEndpoint parse_endpoint(const YAML::Node& node) {
    InterfaceEndpoint ep;
    ep.component = as_or<std::string>(node, "component", "");
    ep.surface = as_or<std::string>(node, "surface", "");
    ep.port_layer = as_or<std::string>(node, "port_layer", "");
    return ep;
}

// The warn sink is threaded in rather than left to the caller because the note
// for an unrecognised vocabulary member has to be produced HERE, at parse, and
// not inside validate: a consumer running with LoadOptions::validate = false is
// the one most likely to meet a document from a newer minor, and a note that
// fires only under validation is delivered on the default path and dropped on
// the path an orchestrator actually takes. The sink is internal API; the public
// contract is LoadOptions::on_warn.
Interface parse_interface(const YAML::Node& node,
                          const std::function<void(const std::string&)>& warn) {
    if (!node["id"] || node["id"].IsNull()) {
        throw ChipletFormatError("interface missing required field: id");
    }
    if (!node["type"] || node["type"].IsNull()) {
        throw ChipletFormatError("interface missing required field: type");
    }
    Interface iface;
    iface.id = node["id"].as<std::string>();
    iface.type = node["type"].as<std::string>();
    // Carried, not refused. The format owns the vocabulary, the schema closes it
    // for WRITERS, and a consumer that cannot act on an unrecognised member
    // refuses the ELEMENT; refusing the DOCUMENT here would turn every future
    // enum member into a MAJOR for everyone downstream.
    if (warn && !is_known_interface_type(iface.type)) {
        std::string known;
        for (const char* k : kKnownInterfaceTypes) {
            if (!known.empty()) known += ", ";
            known += k;
        }
        warn("interface '" + iface.id + "' has an interface type this reader "
             "does not know, '" + iface.type + "'; it is carried through "
             "verbatim. Known types are " + known +
             " (docs/CHIPLET_FORMAT_SPEC.md, validation rule 4)");
    }
    if (node["from"]) iface.from = parse_endpoint(node["from"]);
    if (node["to"]) iface.to = parse_endpoint(node["to"]);
    if (node["physical"]) {
        InterfacePhysical phys;
        phys.pitch = as_or<double>(node["physical"], "pitch", 0.0);
        phys.diameter = as_or<double>(node["physical"], "diameter", 0.0);
        phys.height = as_or<double>(node["physical"], "height", 0.0);
        iface.physical = phys;
    }
    return iface;
}

Netlist parse_netlist(const YAML::Node& node) {
    Netlist nl;
    nl.present = true;
    if (node["nets"] && node["nets"].IsSequence()) {
        for (const auto& netNode : node["nets"]) {
            if (!netNode["name"] || netNode["name"].IsNull()) {
                throw ChipletFormatError("netlist net missing required field: name");
            }
            Net net;
            net.name = netNode["name"].as<std::string>();
            net.net_class = as_or<std::string>(netNode, "class", "signal");
            net.external = as_or<bool>(netNode, "external", false);
            if (netNode["connections"] && netNode["connections"].IsSequence()) {
                for (const auto& connNode : netNode["connections"]) {
                    NetConnection conn;
                    conn.component = as_or<std::string>(connNode, "component", "");
                    conn.pin = as_or<std::string>(connNode, "pin", "");
                    conn.layer = as_or<std::string>(connNode, "layer", "");
                    net.connections.push_back(std::move(conn));
                }
            }
            nl.nets.push_back(std::move(net));
        }
    }
    nl.external_netlist = as_or<std::string>(node, "external_netlist", "");
    return nl;
}

// Parse a "MAJOR.MINOR" version string into (major, minor). Returns nullopt for
// anything that is not exactly two non-negative integers separated by one dot.
// Note: yaml-cpp keeps a quoted "1.10" verbatim (-> 1,10), where PyYAML would
// have folded an UNQUOTED 1.10 to "1.1"; the spec requires the field be quoted.
std::optional<std::pair<int, int>> parse_version_parts(const std::string& fv) {
    const auto dot = fv.find('.');
    if (dot == std::string::npos || fv.find('.', dot + 1) != std::string::npos) {
        return std::nullopt;  // zero dots, or more than one
    }
    const std::string majs = fv.substr(0, dot);
    const std::string mins = fv.substr(dot + 1);
    if (majs.empty() || mins.empty()) return std::nullopt;
    auto all_digits = [](const std::string& s) {
        for (char c : s) if (c < '0' || c > '9') return false;
        return true;
    };
    if (!all_digits(majs) || !all_digits(mins)) return std::nullopt;
    try {
        return std::make_pair(std::stoi(majs), std::stoi(mins));
    } catch (const std::exception&) {
        return std::nullopt;
    }
}

// Parse a governed-sidecar version into (major, minor). Same digits-only rule as
// parse_version_parts, and one difference inherited rather than chosen: a
// MAJOR.MINOR.PATCH spelling is allowed because emitters already write "1.0.0".
// The PATCH is parsed only to be discarded; a patch never changes what a
// consumer may assume, so it must never change a verdict.
std::optional<std::pair<int, int>> parse_contract_version_parts(
    const std::string& value) {
    std::vector<std::string> parts;
    std::string current;
    for (char c : value) {
        if (c == '.') { parts.push_back(current); current.clear(); }
        else { current.push_back(c); }
    }
    parts.push_back(current);
    if (parts.size() != 2 && parts.size() != 3) return std::nullopt;
    for (const std::string& part : parts) {
        if (part.empty()) return std::nullopt;
        for (char c : part) if (c < '0' || c > '9') return std::nullopt;
    }
    try {
        return std::make_pair(std::stoi(parts[0]), std::stoi(parts[1]));
    } catch (const std::exception&) {
        return std::nullopt;
    }
}

// A consumer's declared acceptance, normalized to major -> (minor floor,
// spelling), mirroring the Python _accepted_map. Two floors for one major are a
// PROGRAMMING error, not a data error: there is no verdict to give, so it is
// refused at call time with std::invalid_argument and never at read time.
using AcceptedMap = std::map<int, std::pair<int, std::string>>;

AcceptedMap accepted_map(
    const std::vector<std::string>& accepted, const std::string& name,
    const std::function<std::optional<std::pair<int, int>>(const std::string&)>&
        parse) {
    if (accepted.empty()) {
        throw std::invalid_argument(
            name + " declares no accepted version; a consumer that accepts "
            "nothing can read nothing");
    }
    AcceptedMap out;
    for (const std::string& entry : accepted) {
        const auto parsed = parse(entry);
        if (!parsed) {
            throw std::invalid_argument(
                "supported version '" + entry + "' for " + name +
                " is not a \"MAJOR.MINOR\" string");
        }
        const auto found = out.find(parsed->first);
        if (found != out.end()) {
            throw std::invalid_argument(
                name + " declares two accepted versions with major " +
                std::to_string(parsed->first) + " ('" + found->second.second +
                "' and '" + entry + "'); the set carries one MAJOR.MINOR floor "
                "per major");
        }
        out.emplace(parsed->first, std::make_pair(parsed->second, entry));
    }
    return out;
}

// "major 1 (e.g. \"1.0\")", or every accepted major when there is more than one.
// A refusal that named one major while the consumer accepted two would send the
// producer to fix the wrong end of a transition window.
std::string accepted_phrase(const AcceptedMap& accepted) {
    std::string majors;
    std::string spellings;
    for (const auto& entry : accepted) {  // std::map: ordered by major
        if (!majors.empty()) { majors += ", "; spellings += ", "; }
        majors += std::to_string(entry.first);
        spellings += "\"" + entry.second.second + "\"";
    }
    const std::string head = accepted.size() == 1 ? "major " : "majors ";
    return head + majors + " (e.g. " + spellings + ")";
}

// Up-front document gate: fail fast on the document-level invariants exactly
// where the C++ host reader does, before any section is consumed.
void check_document_gate(const YAML::Node& root, const std::string& formatVersion,
                         const Metadata& metadata, bool allow_intermediate,
                         const std::function<void(const std::string&)>& on_warn) {
    if (!root["format_version"]) {
        throw ChipletFormatError("missing required key: format_version");
    }
    check_format_version(formatVersion, on_warn);
    if (metadata.finalize_required && !allow_intermediate) {
        const std::string finalizer = metadata.finalizer.empty()
            ? "hyp_to_gds.py --update-chiplet-file" : metadata.finalizer;
        throw ChipletFormatError(
            "this is an intermediate .chiplet (_metadata.finalize_required: "
            "true); run " + finalizer + " to finalize, or pass "
            "allow_intermediate=true");
    }
    if (!root["assembly"] || !root["assembly"].IsMap()) {
        throw ChipletFormatError("missing or invalid 'assembly' section");
    }
    const YAML::Node name = root["assembly"]["name"];
    if (!name || name.IsNull() || name.as<std::string>("").empty()) {
        throw ChipletFormatError("assembly.name is required");
    }
}

void emit_technology_fields(YAML::Emitter& out, const Technology& tech) {
    if (!tech.description.empty()) {
        out << YAML::Key << "description" << YAML::Value << tech.description;
    }
    if (!tech.layer_properties.empty()) {
        out << YAML::Key << "layer_properties" << YAML::Value
            << tech.layer_properties;
    }
    // Emitted only when engaged, so a technology without a stackup round-trips
    // without gaining a key it never had.
    if (!tech.stackup.empty()) {
        out << YAML::Key << "stackup" << YAML::Value << tech.stackup;
    }
    if (tech.has_dbu) {
        out << YAML::Key << "dbu" << YAML::Value << tech.dbu;
    }
}

}  // namespace

bool is_known_interface_type(const std::string& t) {
    for (const char* k : kKnownInterfaceTypes) {
        if (t == k) return true;
    }
    return false;
}

std::string check_format_version(
    const std::string& fv,
    const std::function<void(const std::string&)>& on_warn) {
    const auto parsed = parse_version_parts(fv);
    if (!parsed) {
        throw ChipletFormatError(
            "malformed format_version '" + fv +
            "'; expected a quoted \"MAJOR.MINOR\" string");
    }
    const int major = parsed->first;
    const int minor = parsed->second;
    const AcceptedMap accepted = accepted_map(
        std::vector<std::string>(ACCEPTED_FORMAT_VERSIONS.begin(),
                                 ACCEPTED_FORMAT_VERSIONS.end()),
        "format_version", parse_version_parts);
    const auto entry = accepted.find(major);
    if (entry == accepted.end()) {
        throw ChipletFormatError(
            "unsupported format_version '" + fv + "'; this reader supports " +
            accepted_phrase(accepted));
    }
    const int floor_minor = entry->second.first;
    const std::string& floor = entry->second.second;
    const std::string normalized =
        std::to_string(major) + "." + std::to_string(minor);
    if (minor > floor_minor && on_warn) {
        on_warn("format_version '" + fv + "' is newer than this reader's \"" +
                floor + "\" (same major " + std::to_string(major) +
                "); reading it as \"" + floor +
                "\" and ignoring unknown additions");
    }
    return normalized;
}

std::string check_contract_version(
    const std::string& value,
    const std::vector<std::string>& accepted_versions,
    const std::string& name,
    const std::function<void(const std::string&)>& on_warn) {
    const AcceptedMap accepted =
        accepted_map(accepted_versions, name, parse_contract_version_parts);
    const auto parsed = parse_contract_version_parts(value);
    if (!parsed) {
        throw ChipletFormatError(
            name + ": malformed version '" + value +
            "'; expected a quoted \"MAJOR.MINOR\" or \"MAJOR.MINOR.PATCH\" "
            "string");
    }
    const int major = parsed->first;
    const int minor = parsed->second;
    const auto entry = accepted.find(major);
    if (entry == accepted.end()) {
        throw ChipletFormatError(
            name + ": unsupported version '" + value + "'; this consumer "
            "supports " + accepted_phrase(accepted));
    }
    const int floor_minor = entry->second.first;
    const std::string& floor = entry->second.second;
    const std::string normalized =
        std::to_string(major) + "." + std::to_string(minor);
    if (minor > floor_minor && on_warn) {
        on_warn(name + ": version '" + value + "' is newer than the supported \""
                + floor + "\" (same major " + std::to_string(major) +
                "); reading it as \"" + floor +
                "\" and ignoring unknown additions");
    }
    return normalized;
}

const Technology* ChipletDocument::technology(const std::string& id) const {
    for (const auto& t : technologies) {
        if (t.id == id) return &t;
    }
    if (interconnect && interconnect->technology &&
        interconnect->technology->id == id) {
        return &interconnect->technology.value();
    }
    return nullptr;
}

void validate(const ChipletDocument& doc, bool allow_intermediate,
              const std::function<void(const std::string&)>& on_warn) {
    check_format_version(doc.format_version, on_warn);
    if (doc.metadata.finalize_required && !allow_intermediate) {
        const std::string finalizer = doc.metadata.finalizer.empty()
            ? "hyp_to_gds.py --update-chiplet-file" : doc.metadata.finalizer;
        throw ChipletFormatError(
            "this is an intermediate .chiplet (_metadata.finalize_required: "
            "true); run " + finalizer + " to finalize, or pass "
            "allow_intermediate=true");
    }
    if (doc.assembly.name.empty()) {
        throw ChipletFormatError("assembly.name is required");
    }
    for (const auto& c : doc.components) {
        if (c.id.empty()) {
            throw ChipletFormatError("component missing required field: id");
        }
        if (c.type.empty()) {
            throw ChipletFormatError("component '" + c.id +
                                     "' missing required field: type");
        }
    }
    for (const auto& iface : doc.interfaces) {
        if (iface.id.empty()) {
            throw ChipletFormatError("interface missing required field: id");
        }
        // Rule 4 is an id and a type, and nothing about which type: an
        // unrecognised member is carried and reported on the warn channel at
        // parse, never refused here or on the write path.
        if (iface.type.empty()) {
            throw ChipletFormatError("interface '" + iface.id +
                                     "' missing required field: type");
        }
    }
    for (const auto& net : doc.netlist.nets) {
        if (net.name.empty()) {
            throw ChipletFormatError("netlist net missing required field: name");
        }
    }
    check_pad_usage(doc);
}

ChipletDocument loads(const std::string& text, const LoadOptions& opts) {
    // Before yaml-cpp, deliberately: on a document carrying one of the three
    // forbidden line breaks the two reference parsers disagree about what the
    // document even is, and once a parser has been over the bytes the evidence
    // is gone. The Python reference runs the same check in the same position.
    check_line_breaks(text);

    YAML::Node root;
    try {
        root = YAML::Load(text);
    } catch (const YAML::Exception& e) {
        throw ChipletFormatError(std::string("YAML parse error: ") + e.what());
    }

    if (!root || root.IsNull()) {
        throw ChipletFormatError("empty .chiplet document");
    }
    if (!root.IsMap()) {
        throw ChipletFormatError("top-level .chiplet document must be a mapping");
    }

    // The grammar runs over the SOURCE TEXT, which is the only place the exact
    // bytes of a block exist. An unattributable line at column zero (a quoted
    // key, an explicit key, a bare key outside the grammar, anything else there
    // that is not a key line, a comment, a directive, a document marker or a
    // sequence entry) leaves the document NOT SPLITTABLE (`not_splittable`
    // explains why and the blocks must not be used); the document itself is
    // valid and is still read, because flow rule 1 says a reader that cannot
    // handle the flow block must not reject the file.
    // What that costs is the ability to write it back, and that is where it is
    // charged: see dumps().
    std::string not_splittable;
    const std::vector<std::pair<std::string, std::string>> blocks =
        split_top_level_blocks(text, &not_splittable);

    ChipletDocument doc;
    doc.format_version = as_or<std::string>(root, "format_version", "");

    if (root["_metadata"] && root["_metadata"].IsMap()) {
        doc.metadata.present = true;
        doc.metadata.finalize_required =
            as_or<bool>(root["_metadata"], "finalize_required", false);
        doc.metadata.finalizer =
            as_or<std::string>(root["_metadata"], "finalizer", "");
    }

    // Non-fatal reader notes. opts.on_warn is the single NORMATIVE channel:
    // every event, undeduplicated, in the order it happened. Pushing onto
    // doc.warnings as well is non-normative convenience for a host that would
    // rather read a vector than set a callback. Never stderr, never a throw
    // (fatal conditions throw ChipletFormatError instead).
    auto warn_sink = [&doc, &opts](const std::string& msg) {
        doc.warnings.push_back(msg);
        if (opts.on_warn) opts.on_warn(msg);
    };
    if (opts.validate) {
        check_document_gate(root, doc.format_version, doc.metadata,
                            opts.allow_intermediate, warn_sink);
    }

    if (root["assembly"]) {
        const YAML::Node& a = root["assembly"];
        doc.assembly.name = as_or<std::string>(a, "name", "");
        doc.assembly.description = as_or<std::string>(a, "description", "");
        doc.assembly.author = as_or<std::string>(a, "author", "");
        doc.assembly.created = as_or<std::string>(a, "created", "");
        doc.assembly.modified = as_or<std::string>(a, "modified", "");
        doc.assembly.units = as_or<std::string>(a, "units", "");
        doc.assembly.assembly_gds = as_or<std::string>(a, "assembly_gds", "");
        doc.assembly.io_technology = as_or<std::string>(a, "io_technology", "");
    }

    if (root["technologies"]) {
        if (!root["technologies"].IsMap()) {
            throw ChipletFormatError("'technologies' must be a mapping");
        }
        for (const auto& item : root["technologies"]) {
            doc.technologies.push_back(
                parse_technology(item.first.as<std::string>(), item.second));
        }
    }

    if (root["connection_stacks"]) {
        if (!root["connection_stacks"].IsMap()) {
            throw ChipletFormatError("'connection_stacks' must be a mapping");
        }
        for (const auto& item : root["connection_stacks"]) {
            doc.connection_stacks.push_back(
                parse_connection_stack(item.first.as<std::string>(), item.second));
        }
    }

    if (root["components"]) {
        if (!root["components"].IsSequence()) {
            throw ChipletFormatError("'components' must be a sequence");
        }
        for (const auto& compNode : root["components"]) {
            doc.components.push_back(parse_component(compNode));
        }
    }

    // Interconnect block is recognized only when it carries an adapter,
    // mirroring the host reader.
    if (root["interconnect"] && root["interconnect"]["adapter"]) {
        Interconnect ic;
        ic.adapter = root["interconnect"]["adapter"].as<std::string>();
        if (root["interconnect"]["technology"]) {
            ic.technology =
                parse_technology(ic.adapter, root["interconnect"]["technology"]);
        }
        doc.interconnect = std::move(ic);
    }

    if (root["interfaces"]) {
        if (!root["interfaces"].IsSequence()) {
            throw ChipletFormatError("'interfaces' must be a sequence");
        }
        for (const auto& ifaceNode : root["interfaces"]) {
            // warn_sink, not opts.on_warn: the vocabulary note is produced at
            // parse under either setting of opts.validate.
            doc.interfaces.push_back(parse_interface(ifaceNode, warn_sink));
        }
    }

    if (root["netlist"]) {
        doc.netlist = parse_netlist(root["netlist"]);
    }

    if (root["flow"]) {
        doc.has_flow = true;
        const std::string* slice = nullptr;
        if (not_splittable.empty()) {
            for (const auto& block : blocks) {
                if (block.first == "flow") {
                    slice = &block.second;
                    break;
                }
            }
        }
        if (slice == nullptr) {
            // The document has a flow block whose bytes the grammar cannot
            // delimit: the file is not splittable at all, or the block is not a
            // bare `flow:` at column zero (a flow-style document, or `flow :`).
            // The document is still valid and still loads, per flow rule 1. What
            // it loses is the write path: flow_yaml stays empty, the source is
            // recorded as NotDelimitable, and dumps() refuses rather than drop
            // the block or emit a node dump as if it were the source.
            doc.flow_source = FlowSource::NotDelimitable;
        } else {
            doc.flow_yaml = *slice;
            doc.flow_source = FlowSource::Slice;
        }
    }

    // Rule 8 is the one check that needs the WHOLE document (an interface, the
    // component it names and that component's inline pads), so it runs here,
    // after the parse, under the same gate as the document-level checks.
    if (opts.validate) check_pad_usage(doc);

    return doc;
}

ChipletDocument load(const std::string& path, const LoadOptions& opts) {
    std::ifstream file(path);
    if (!file.is_open()) {
        throw ChipletFormatError("could not open file for reading: " + path);
    }
    std::stringstream buffer;
    buffer << file.rdbuf();
    return loads(buffer.str(), opts);
}

// The emit pass. `quote_all_strings` is not a caller-facing option and never
// becomes one: it is the second half of the writer's line-break rule. yaml-cpp
// writes U+2028 and U+2029 as RAW bytes in every style, double-quoted included
// (measured on 0.8.0), and re-escaping them in the finished text is
// only sound where the scalar carrying them is double-quoted. So when the first
// pass turns out to contain one, the document is emitted a second time with
// every string double-quoted and the raw bytes are then replaced by \N, \L and
// \P. The retry costs one extra emit for a document that should not exist, and
// the ordinary path pays a substring search.
//
// NEL is NOT in that sentence and the difference matters. yaml-cpp escapes NEL
// by itself, as \x85 (measured on 0.8.0: emitting "a<NEL>b" double-quoted gives
// the bytes 61 5c 78 38 35 62), so the raw character never survives the first
// pass and this table's NEL entry is never reached on the write path. The entry
// stays because the same table drives the refusal message, where it is read.
// The consequence is for the OTHER writer: PyYAML picks \N for U+0085, and this
// reader decodes \N to a bare 0x85, which is not valid UTF-8 on its own, so the
// Python reference writer had to be pushed onto the \x85 spelling to keep a
// document written there readable here. See the Python dumper's
// ESCAPE_REPLACEMENTS override and test_nel_escape_hazard_is_pinned below.
static std::string dumps_text(const ChipletDocument& doc,
                              const DumpOptions& opts, bool quote_all_strings) {
    // Not validation, and so not under opts.validate: this document simply
    // cannot be written. It was read from a file whose flow block the top-level
    // block grammar could not delimit, so the block's bytes were never captured.
    // A writer has three options here and two of them are silent lies: drop the
    // block, or emit a node dump in the place the source text belongs. It takes
    // the third and says so. A host that re-authors the flow (assigns flow_yaml)
    // may save normally.
    if (doc.has_flow && doc.flow_yaml.empty() &&
        doc.flow_source == FlowSource::NotDelimitable) {
        throw ChipletFormatError(
            "this document carries a flow block the top-level block grammar "
            "could not delimit (it is not written as a bare `flow:` key line at "
            "column zero, or the file is not splittable at all because some line "
            "at column zero is one no top-level key owns), so its source bytes "
            "were never captured and flow rule 4 cannot be honoured on write. "
            "Re-author the flow through this host before saving "
            "(docs/CHIPLET_FORMAT_SPEC.md, top-level block grammar)");
    }
    if (opts.validate) {
        // Writing an intermediate (finalize_required) document is legitimate.
        validate(doc, /*allow_intermediate=*/true);
    }

    YAML::Emitter out;
    if (quote_all_strings) out.SetStringFormat(YAML::DoubleQuoted);
    out << YAML::BeginMap;

    // Lossy writer (H-B crux): this reconstructs YAML from the struct model,
    // which does NOT carry unknown top-level keys, so it stamps its own
    // supported version rather than echoing a possibly-higher input version --
    // the stamped version must describe the bytes written, and these bytes are
    // supported-version content. (A lossless passthrough writer preserves a
    // higher minor; this is not one.)
    const std::string fv = SUPPORTED_FORMAT_VERSION;
    out << YAML::Key << "format_version" << YAML::Value << YAML::DoubleQuoted << fv;

    if (doc.metadata.finalize_required || !doc.metadata.finalizer.empty()) {
        out << YAML::Key << "_metadata" << YAML::Value << YAML::BeginMap;
        if (doc.metadata.finalize_required) {
            out << YAML::Key << "finalize_required" << YAML::Value << true;
        }
        if (!doc.metadata.finalizer.empty()) {
            out << YAML::Key << "finalizer" << YAML::Value << doc.metadata.finalizer;
        }
        out << YAML::EndMap;
    }

    // Assembly metadata.
    out << YAML::Key << "assembly" << YAML::Value << YAML::BeginMap;
    out << YAML::Key << "name" << YAML::Value << doc.assembly.name;
    if (!doc.assembly.description.empty())
        out << YAML::Key << "description" << YAML::Value << doc.assembly.description;
    if (!doc.assembly.author.empty())
        out << YAML::Key << "author" << YAML::Value << doc.assembly.author;
    if (!doc.assembly.created.empty())
        out << YAML::Key << "created" << YAML::Value << doc.assembly.created;
    if (!doc.assembly.modified.empty())
        out << YAML::Key << "modified" << YAML::Value << doc.assembly.modified;
    if (!doc.assembly.units.empty())
        out << YAML::Key << "units" << YAML::Value << doc.assembly.units;
    if (!doc.assembly.assembly_gds.empty())
        out << YAML::Key << "assembly_gds" << YAML::Value << doc.assembly.assembly_gds;
    if (!doc.assembly.io_technology.empty())
        out << YAML::Key << "io_technology" << YAML::Value << doc.assembly.io_technology;
    out << YAML::EndMap;

    // Technologies.
    if (!doc.technologies.empty()) {
        out << YAML::Key << "technologies" << YAML::Value << YAML::BeginMap;
        for (const auto& tech : doc.technologies) {
            out << YAML::Key << tech.id << YAML::Value << YAML::BeginMap;
            emit_technology_fields(out, tech);
            out << YAML::EndMap;
        }
        out << YAML::EndMap;
    }

    // Interconnect (adapter + optional PDK-backed identity).
    if (doc.interconnect) {
        out << YAML::Key << "interconnect" << YAML::Value << YAML::BeginMap;
        out << YAML::Key << "adapter" << YAML::Value << doc.interconnect->adapter;
        if (doc.interconnect->technology) {
            out << YAML::Key << "technology" << YAML::Value << YAML::BeginMap;
            emit_technology_fields(out, doc.interconnect->technology.value());
            out << YAML::EndMap;
        }
        out << YAML::EndMap;
    }

    // Connection stacks.
    if (!doc.connection_stacks.empty()) {
        out << YAML::Key << "connection_stacks" << YAML::Value << YAML::BeginMap;
        for (const auto& stack : doc.connection_stacks) {
            out << YAML::Key << stack.id << YAML::Value << YAML::BeginMap;
            if (!stack.description.empty()) {
                out << YAML::Key << "description" << YAML::Value << stack.description;
            }
            if (!stack.layers.empty()) {
                out << YAML::Key << "layers" << YAML::Value << YAML::BeginSeq;
                for (const auto& layer : stack.layers) {
                    out << YAML::Flow << YAML::BeginMap;
                    out << YAML::Key << "name" << YAML::Value << layer.name;
                    out << YAML::Key << "material" << YAML::Value << layer.material;
                    out << YAML::Key << "height" << YAML::Value << layer.height;
                    out << YAML::Key << "diameter" << YAML::Value << layer.diameter;
                    out << YAML::EndMap;
                }
                out << YAML::EndSeq;
            }
            out << YAML::EndMap;
        }
        out << YAML::EndMap;
    }

    // Components.
    if (!doc.components.empty()) {
        out << YAML::Key << "components" << YAML::Value << YAML::BeginSeq;
        for (const auto& comp : doc.components) {
            out << YAML::BeginMap;
            out << YAML::Key << "id" << YAML::Value << comp.id;
            out << YAML::Key << "type" << YAML::Value << comp.type;
            if (comp.anchor) {
                out << YAML::Key << "anchor" << YAML::Value << comp.anchor.value();
            }
            if (!comp.technology.empty())
                out << YAML::Key << "technology" << YAML::Value << comp.technology;
            if (!comp.connection.empty())
                out << YAML::Key << "connection" << YAML::Value << comp.connection;
            if (!comp.layout.empty())
                out << YAML::Key << "layout" << YAML::Value << comp.layout;

            if (!comp.cells.empty()) {
                if (comp.cells.size() == 1) {
                    out << YAML::Key << "top_cell" << YAML::Value << comp.cells[0];
                } else {
                    out << YAML::Key << "cells" << YAML::Value << YAML::Flow
                        << YAML::BeginSeq;
                    for (const auto& cell : comp.cells) out << cell;
                    out << YAML::EndSeq;
                }
            }

            const auto& pos = comp.position;
            if (pos.x != 0 || pos.y != 0 || pos.z != 0) {
                out << YAML::Key << "position" << YAML::Value << YAML::Flow
                    << YAML::BeginMap;
                out << YAML::Key << "x" << YAML::Value << pos.x;
                out << YAML::Key << "y" << YAML::Value << pos.y;
                out << YAML::Key << "z" << YAML::Value << pos.z;
                out << YAML::EndMap;
            }

            if (comp.rotation.z != 0) {
                out << YAML::Key << "rotation" << YAML::Value << YAML::Flow
                    << YAML::BeginMap;
                out << YAML::Key << "z" << YAML::Value << comp.rotation.z;
                out << YAML::EndMap;
            }

            if (!comp.orientation.empty() && comp.orientation != "face_up") {
                out << YAML::Key << "orientation" << YAML::Value << comp.orientation;
            }

            const auto& dims = comp.dimensions;
            if (dims.width != 0 || dims.height != 0 || dims.thickness != 0) {
                out << YAML::Key << "dimensions" << YAML::Value << YAML::Flow
                    << YAML::BeginMap;
                out << YAML::Key << "width" << YAML::Value << dims.width;
                out << YAML::Key << "height" << YAML::Value << dims.height;
                out << YAML::Key << "thickness" << YAML::Value << dims.thickness;
                out << YAML::EndMap;
            }

            // Emitted only when engaged, so files without an attachment surface
            // round-trip byte-identically (the legacy thickness-as-mount case).
            if (comp.attachment_surface_z) {
                out << YAML::Key << "attachment_surface_z" << YAML::Value
                    << comp.attachment_surface_z.value();
            }

            if (comp.array) {
                const auto& arr = comp.array.value();
                out << YAML::Key << "array" << YAML::Value << YAML::BeginMap;
                out << YAML::Key << "pattern" << YAML::Value << arr.pattern;
                out << YAML::Key << "count" << YAML::Value << YAML::Flow
                    << YAML::BeginMap;
                out << YAML::Key << "x" << YAML::Value << arr.count_x;
                out << YAML::Key << "y" << YAML::Value << arr.count_y;
                out << YAML::EndMap;
                out << YAML::Key << "pitch" << YAML::Value << YAML::Flow
                    << YAML::BeginMap;
                out << YAML::Key << "x" << YAML::Value << arr.pitch_x;
                out << YAML::Key << "y" << YAML::Value << arr.pitch_y;
                out << YAML::EndMap;
                out << YAML::Key << "start_position" << YAML::Value << YAML::Flow
                    << YAML::BeginMap;
                out << YAML::Key << "x" << YAML::Value << arr.start_position.x;
                out << YAML::Key << "y" << YAML::Value << arr.start_position.y;
                out << YAML::Key << "z" << YAML::Value << arr.start_position.z;
                out << YAML::EndMap;
                out << YAML::EndMap;
            }

            if (!comp.metadata.empty()) {
                out << YAML::Key << "metadata" << YAML::Value << YAML::BeginMap;
                for (const auto& [key, value] : comp.metadata) {
                    out << YAML::Key << key << YAML::Value << value;
                }
                out << YAML::EndMap;
            }

            if (!comp.io_pads.empty()) {
                out << YAML::Key << "io_pads" << YAML::Value << YAML::BeginSeq;
                for (const auto& pad : comp.io_pads) {
                    out << YAML::BeginMap;
                    out << YAML::Key << "id" << YAML::Value << pad.id;
                    out << YAML::Key << "io_class" << YAML::Value << pad.io_class;
                    if (!pad.net.empty())
                        out << YAML::Key << "net" << YAML::Value << pad.net;
                    out << YAML::Key << "position" << YAML::Value << YAML::Flow
                        << YAML::BeginMap;
                    out << YAML::Key << "x" << YAML::Value << pad.pos_x;
                    out << YAML::Key << "y" << YAML::Value << pad.pos_y;
                    out << YAML::EndMap;
                    out << YAML::Key << "size" << YAML::Value << YAML::Flow
                        << YAML::BeginMap;
                    out << YAML::Key << "x" << YAML::Value << pad.size_x;
                    out << YAML::Key << "y" << YAML::Value << pad.size_y;
                    out << YAML::EndMap;
                    if (!pad.layer.empty())
                        out << YAML::Key << "layer" << YAML::Value << pad.layer;
                    out << YAML::EndMap;
                }
                out << YAML::EndSeq;
            }

            out << YAML::EndMap;
        }
        out << YAML::EndSeq;
    }

    // Interfaces.
    if (!doc.interfaces.empty()) {
        out << YAML::Key << "interfaces" << YAML::Value << YAML::BeginSeq;
        for (const auto& iface : doc.interfaces) {
            out << YAML::BeginMap;
            out << YAML::Key << "id" << YAML::Value << iface.id;
            out << YAML::Key << "type" << YAML::Value << iface.type;
            if (iface.from) {
                out << YAML::Key << "from" << YAML::Value << YAML::Flow
                    << YAML::BeginMap;
                out << YAML::Key << "component" << YAML::Value << iface.from->component;
                out << YAML::Key << "surface" << YAML::Value << iface.from->surface;
                out << YAML::Key << "port_layer" << YAML::Value << iface.from->port_layer;
                out << YAML::EndMap;
            }
            if (iface.to) {
                out << YAML::Key << "to" << YAML::Value << YAML::Flow
                    << YAML::BeginMap;
                out << YAML::Key << "component" << YAML::Value << iface.to->component;
                out << YAML::Key << "surface" << YAML::Value << iface.to->surface;
                out << YAML::Key << "port_layer" << YAML::Value << iface.to->port_layer;
                out << YAML::EndMap;
            }
            if (iface.physical) {
                out << YAML::Key << "physical" << YAML::Value << YAML::Flow
                    << YAML::BeginMap;
                out << YAML::Key << "pitch" << YAML::Value << iface.physical->pitch;
                out << YAML::Key << "diameter" << YAML::Value << iface.physical->diameter;
                out << YAML::Key << "height" << YAML::Value << iface.physical->height;
                out << YAML::EndMap;
            }
            out << YAML::EndMap;
        }
        out << YAML::EndSeq;
    }

    // Netlist.
    if (doc.netlist.present &&
        (!doc.netlist.nets.empty() || !doc.netlist.external_netlist.empty())) {
        out << YAML::Key << "netlist" << YAML::Value << YAML::BeginMap;
        if (!doc.netlist.nets.empty()) {
            out << YAML::Key << "nets" << YAML::Value << YAML::BeginSeq;
            for (const auto& net : doc.netlist.nets) {
                out << YAML::BeginMap;
                out << YAML::Key << "name" << YAML::Value << net.name;
                out << YAML::Key << "class" << YAML::Value << net.net_class;
                if (net.external) {
                    out << YAML::Key << "external" << YAML::Value << net.external;
                }
                if (!net.connections.empty()) {
                    out << YAML::Key << "connections" << YAML::Value << YAML::BeginSeq;
                    for (const auto& conn : net.connections) {
                        out << YAML::Flow << YAML::BeginMap;
                        out << YAML::Key << "component" << YAML::Value << conn.component;
                        out << YAML::Key << "pin" << YAML::Value << conn.pin;
                        if (!conn.layer.empty()) {
                            out << YAML::Key << "layer" << YAML::Value << conn.layer;
                        }
                        out << YAML::EndMap;
                    }
                    out << YAML::EndSeq;
                }
                out << YAML::EndMap;
            }
            out << YAML::EndSeq;
        }
        if (!doc.netlist.external_netlist.empty()) {
            out << YAML::Key << "external_netlist" << YAML::Value
                << doc.netlist.external_netlist;
        }
        out << YAML::EndMap;
    }

    out << YAML::EndMap;

    std::string text = std::string(out.c_str()) + "\n";

    // The writer's half of the line-break rule, on the EMITTED section only. A
    // forbidden code point can only be here because a host put one in a struct
    // field: after this release no load produces one. The retry is what makes
    // the replacement below sound, since it is the pass in which every scalar is
    // double-quoted; the flow slice appended after this point is source bytes
    // under rule 4 and is never rewritten.
    if (!quote_all_strings && has_forbidden_line_break(text)) {
        return dumps_text(doc, opts, /*quote_all_strings=*/true);
    }
    if (quote_all_strings) {
        for (const ForbiddenLineBreak& bad : kForbiddenLineBreaks) {
            const std::string raw = bad.utf8;
            for (std::size_t at = text.find(raw); at != std::string::npos;
                 at = text.find(raw, at + 2)) {
                text.replace(at, raw.size(), bad.escape);
            }
        }
        text = unquote_top_level_keys(text);
    }

    // Read the keys of the generated mapping BEFORE appending caller-supplied
    // source. Parsing the final text would let an extra key in flow_yaml define
    // its own expected output and defeat the ownership check.
    std::vector<std::string> expected_keys;
    for (const auto& entry : YAML::Load(text)) {
        expected_keys.push_back(entry.first.as<std::string>());
    }

    // The flow block, byte for byte (rule 4). `flow_yaml` is the source slice
    // the reader took, key line included, so it is APPENDED rather than emitted
    // through the node tree: an emitter would re-quote its scalars and drop its
    // comments, and this writer is a host that did not author the block. It goes
    // last, which is where the emitter used to put it.
    if (doc.has_flow && !doc.flow_yaml.empty()) {
        std::string block = doc.flow_yaml;
        const std::size_t nl = block.find('\n');
        const std::string first = line_content(
            nl == std::string::npos ? block : block.substr(0, nl + 1));
        if (top_level_key(first) != "flow") {
            // A document assembled in memory may still carry the pre-slice
            // spelling, the flow VALUE without its key line. Wrap it through the
            // node tree so the emitted document keeps a `flow:` key either way;
            // that path is lossy, which is exactly why the reader stopped
            // producing it.
            YAML::Node wrapper;
            wrapper["flow"] = YAML::Load(block);
            block = YAML::Dump(wrapper);
        }
        if (block.empty() || block.back() != '\n') block += "\n";
        text += block;
        expected_keys.emplace_back("flow");
    }

    // Check the COMPLETE output, including the preserved source slice. This is
    // a writer invariant, not optional document validation. Only the generated
    // mapping has literal top-level keys; flow_yaml can contain arbitrary text.
    std::string not_splittable;
    const auto blocks = split_top_level_blocks(text, &not_splittable);
    if (!not_splittable.empty()) {
        throw ChipletFormatError("writer output cannot be split: " + not_splittable);
    }
    std::size_t key_index = 0;
    std::size_t line_number = 1;
    for (const auto& block : blocks) {
        if (!block.first.empty()) {
            if (key_index >= expected_keys.size() ||
                block.first != expected_keys[key_index]) {
                throw ChipletFormatError(
                    "writer output line " + std::to_string(line_number) +
                    ": top-level key (" + block.first +
                    ") is not the next key the writer emitted");
            }
            ++key_index;
        }
        for (const char ch : block.second) {
            if (ch == '\n') ++line_number;
        }
    }
    if (key_index != expected_keys.size()) {
        throw ChipletFormatError(
            "writer output line " + std::to_string(line_number) +
            ": the split did not recover every key the writer emitted");
    }
    return text;
}

std::string dumps(const ChipletDocument& doc, const DumpOptions& opts) {
    return dumps_text(doc, opts, /*quote_all_strings=*/false);
}

void dump(const ChipletDocument& doc, const std::string& path,
          const DumpOptions& opts) {
    const std::string text = dumps(doc, opts);
    std::ofstream file(path);
    if (!file.is_open()) {
        throw ChipletFormatError("could not open file for writing: " + path);
    }
    file << text;
}

}  // namespace chiplet_format_io
